backend:
  name: github
  repo: walusimbikigozi-cpu/wilco-africa
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
    - name: "pages"
    label: "Pages"
    files:
            - file: "index.html"
        label: "Homepage"
        name: "home"
        fields:
                    - {label: "Title", name: "title", widget: "string"}
                    - {label: "Headline", name: "headline", widget: "string"}
                    - {label: "Body", name: "body", widget: "markdown"}
